{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "inmidst.name" . }}-postgres
spec:
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector:
    app: {{ include "inmidst.name" . }}-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inmidst.name" . }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "inmidst.name" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "inmidst.name" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "inmidst.fullname" . }}-secrets
                  key: postgres-password
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
{{- end }}
