apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inmidst.fullname" . }}-secrets
  labels:
    {{- include "inmidst.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc | quote }}
  {{- if .Values.secrets.stripeSecretKey }}
  stripe-secret-key: {{ .Values.secrets.stripeSecretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.stripeWebhookSecret }}
  stripe-webhook-secret: {{ .Values.secrets.stripeWebhookSecret | b64enc | quote }}
  {{- end }}
